title: Jonah Smith
email: smith.jonah@gmail.com
description: Jonah Smith - software engineer
url: "https://jonah-smith.com"
twitter_username: jonahesmith
github_username:  jonahsmith

markdown: kramdown
permalink: /blog/:title
sass:
  sass_dir: assets/css